name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies using Makefile
      - name: Install dependencies
        run: |
          make install

      # Step 4: Run the Flask application with Makefile
      - name: Run Flask application
        run: |
          make run &
          sleep 10  # Allow Flask time to start
name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4

      # Step 2: Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies using Makefile
      - name: Install dependencies
        run: |
          make install

      # Step 4: Run the Flask application with Makefile
      - name: Run Flask application
        run: |
          make run &
          sleep 10  # Allow Flask time to start

      # Step 5: Run tests with pytest
      - name: Run tests with pytest
        run: |
          . venv/bin/activate && pytest
