name: Python Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Check out the code

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies using Makefile
        run: |
          make install

      - name: Lint with flake8
        run: |
          . venv/bin/activate && flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Flask application
        run: |
          make run &
          sleep 10  # Allow Flask time to start

      - name: Run tests with pytest
        run: |
          . venv/bin/activate && pytest
